// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;

namespace FlexPieSample
{
	public partial class BasicFeaturesController : UIViewController
	{
		public BasicFeaturesController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			IEnumerable<PieChartData> pieData = PieChartData.DemoData ();

			pieChart.Binding = "Value";
			pieChart.BindingName = "Name";
			pieChart.ItemsSource = pieData;

		}

		partial void offsetChanged (UISlider sender)
		{
			pieChart.Offset = sender.Value;
		}

		partial void startAngleChanged (UISlider sender)
		{
			pieChart.StartAngle = sender.Value;
		}


		partial void switchValueChanged (UISwitch sender)
		{
			pieChart.Reversed = sender.On;
		}

		partial void valueChanged (UIStepper sender)
		{
			pieChart.InnerRadius = stepper.Value;
			innerRadiusLabel.Text = stepper.Value.ToString();
			innerRadiusLabel.SizeToFit();
		}
	}
}
