// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;

namespace FlexPieSample
{
	public partial class GettingStartedController : UIViewController
	{
		public GettingStartedController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			IEnumerable<PieChartData> pieData = PieChartData.DemoData ();

			pieChart.Binding = "Value";
			pieChart.BindingName = "Name";
			pieChart.ItemsSource = pieData;
			pieChart.Tooltip.IsVisible = true;


			donutChart.Binding = "Value";
			donutChart.BindingName = "Name";
			donutChart.ItemsSource = pieData;
			donutChart.Tooltip.IsVisible = true;
			donutChart.InnerRadius = 0.6;
		}
	}
}
