// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;

namespace FlexPieSample
{
	public partial class SelectionSampleController : UIViewController
	{
		public SelectionSampleController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			positionSelector.SelectedSegment = 4;

			IEnumerable<PieChartData> pieData = PieChartData.DemoData ();

			offsetLabel.Text = stepper.Value.ToString ();

			flexPie.Binding = "Value";
			flexPie.BindingName = "Name";
			flexPie.ItemsSource = pieData;
			flexPie.Tooltip.IsVisible = true;
			flexPie.SelectedItemOffset = stepper.Value;
			flexPie.SelectedItemPosition = Xuni.iOS.ChartCore.Position.Bottom;
			flexPie.IsAnimated = false;
		}

		partial void positionChanged (UISegmentedControl sender)
		{
			flexPie.SelectedItemPosition = (Xuni.iOS.ChartCore.Position)(int)sender.SelectedSegment;
		}

		partial void stepperClicked (UIStepper sender)
		{
			flexPie.SelectedItemOffset = stepper.Value;
			offsetLabel.Text = stepper.Value.ToString ();
		}

		partial void switchAnimation (UISwitch sender)
		{
			flexPie.IsAnimated = sender.On;
		}
	}
}
