// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using System.Collections.Generic;

namespace FlexPieSample
{
	public partial class SnapshotController : UIViewController
	{
		public SnapshotController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			IEnumerable<PieChartData> pieData = PieChartData.DemoData ();

			flexPie.Binding = "Value";
			flexPie.BindingName = "Name";
			flexPie.ItemsSource = pieData;
			flexPie.Tooltip.IsVisible = true;
		}

		partial void doTakeSnapshot (UIBarButtonItem sender)
		{
			UIImage img = new UIImage (flexPie.GetImage ());
			img.SaveToPhotosAlbum ((image, error) => {
				if (error == null)
					new UIAlertView ("Success", "Image was saved to Camera Roll succesfully", null, "OK", null).Show ();
				else
					new UIAlertView ("Failure", error.Description, null, "OK", null).Show ();
			});
		}
	}
}
