// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CalendarSample
{
	public partial class CustomAppearanceController : UIViewController
	{
		public CustomAppearanceController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			calendar.BorderColor = UIColor.Black;
			calendar.BorderWidth = 5.0;

			calendar.HeaderBackgroundColor = new UIColor ((nfloat)(61 / 255.0), (nfloat)(131 / 255.0), (nfloat)(75 / 255.0), (nfloat)1.0);
			calendar.HeaderTextColor = UIColor.White;
			calendar.HeaderFont = UIFont.BoldSystemFontOfSize(28);

			calendar.DayOfWeekFormat = Xuni.iOS.Calendar.XuniDayOfWeekFormat.D;
			calendar.DayOfWeekBackgroundColor = new UIColor((nfloat)(99 / 255.0), (nfloat)(166 / 255.0), (nfloat)(70 / 255.0), (nfloat)1.0);
			calendar.DayOfWeekTextColor = UIColor.White;
			calendar.DayOfWeekFont = UIFont.BoldSystemFontOfSize(20);

			calendar.DayBorderColor = new UIColor((nfloat)(242 / 255.0), (nfloat)(242 / 255.0), (nfloat)(242 / 255.0), (nfloat)1.0);
			calendar.DayBorderWidth = 2;

			calendar.AdjacentDayTextColor = UIColor.Gray;
			calendar.CalendarFont = UIFont.SystemFontOfSize(14);
			calendar.TodayFont = UIFont.ItalicSystemFontOfSize(16);
		}
	}
}
