// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CalendarSample
{
	public partial class GettingStartedController : UIViewController
	{
		public GettingStartedController (IntPtr handle) : base (handle)
		{
		}
	}
}
