// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;
using Xuni.iOS.Calendar;

namespace CalendarSample
{
	public partial class PopupEditorController : UIViewController
	{
		public PopupEditorController (IntPtr handle) : base (handle)
		{
		}

		UIButton pickBtn = null;
		UILabel dateLabel = null;
		UIView view = null;
		XuniCalendar calendar = null;
		NSDateFormatter dateFormatter = null;

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			dateFormatter = new NSDateFormatter ();

			calendar = new XuniCalendar();
			calendar.HeaderBackgroundColor = UIColor.White;
			calendar.Hidden = true;
			calendar.SelectionChanged+=(object sender, SelectionChangedEventArgs e) => 
			{
				dateFormatter.DateFormat = "M/d/yyyy";
				dateLabel.Text = "The date " + dateFormatter.StringFor(e.SelectedDates.StartDate) + " was selected.";
				calendar.Hidden = true;
				if (calendar.Hidden == true) {
						this.View.BackgroundColor = UIColor.White;
						this.NavigationController.NavigationBar.BarTintColor = UIColor.White;
				}

			};

			pickBtn = new UIButton(UIButtonType.System);
			pickBtn.SetTitle("Pick a date", UIControlState.Normal);
			pickBtn.TouchUpInside+=(object sender, EventArgs e) => 
			{
				calendar.Hidden = !calendar.Hidden;
				if (calendar.Hidden == false) {
					this.View.BackgroundColor = UIColor.Gray;
					this.NavigationController.NavigationBar.BarTintColor = UIColor.LightGray;
				}
				else
				{
					this.View.BackgroundColor = UIColor.White;
					this.NavigationController.NavigationBar.BarTintColor = UIColor.White;
				}
			};

			dateLabel = new UILabel();
			dateLabel.Text = "";

			view = new UIView();
			view.BackgroundColor  = UIColor.White;
			view.UserInteractionEnabled = true;
			view.Layer.CornerRadius = 4;

			this.View.Add(pickBtn);
			this.View.Add(dateLabel);
			this.View.Add(view);
			this.View.Add(calendar);


		}

		public override void ViewDidLayoutSubviews ()
		{
			base.ViewDidLayoutSubviews ();
			CGSize size = this.View.Bounds.Size;
			nfloat width = (nfloat)Math.Min (size.Width, size.Height) / 3 * 2;
			pickBtn.Frame = new CGRect(10, 55 + 10, size.Width - 10 - 10, 30);
			dateLabel.Frame = new CGRect((size.Width - 280) / 2, 55 + 50, 280, 30);
			calendar.Frame = new CGRect((size.Width - width) / 2, 55 + 140, width, width);
			view.Frame = new CGRect((size.Width - width) / 2 - 4, 55 + 140 - 4, width + 8, width + 8);
		}

		public override void ViewWillDisappear (bool animated)
		{
			base.ViewWillDisappear (animated);
			this.View.BackgroundColor = UIColor.White;
			this.NavigationController.NavigationBar.BarTintColor = UIColor.White;
		}

	}
}
