// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace CalendarSample
{
	public partial class VerticalOrientationController : UIViewController
	{
		public VerticalOrientationController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			calendar.Orientation = Xuni.iOS.Calendar.XuniCalendarOrientation.Vertical;
		}
	}
}
