// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Foundation;
using UIKit;

using System.Collections.Generic;
using Xuni.iOS.Core;
using Xuni.iOS.ChartCore;
using Xuni.iOS.FlexChart;

namespace FlexChartSample
{
	public partial class ChartAnnotationsController : UIViewController
	{
		public ChartAnnotationsController(IntPtr handle) : base(handle)
		{

		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			chart.BindingX = "Name";

			chart.Series.Add(new Series(chart, "Sales, Sales", "Sales"));
			chart.ChartType = ChartType.Line;
			chart.ItemsSource = SalesData.GetSalesDataList();

			chart.Annotations.Add(new XuniChartPolygonAnnotation(chart)
			{
				IsVisible = true,
				Attachment = XuniChartAnnotationAttachment.Absolute,
				Color = UIColor.Red,
				BorderColor = new UIColor(20.0f / 255.0f, 153.0f / 255.0f, 212.0f / 255.0f, 1.0f),
				BorderWidth = 2,
				TextColor = UIColor.Black,
				Text = "Absolute",
				TooltipText = "Polygon Annotation\\nPaths:[{0,0},{40,40},{80,0},\\n{60,-40},{20,-40}]\\nAttachment:Absolute",
				Points = new XuniPoint[] { new XuniPoint(60, 40), new XuniPoint(20, 80), new XuniPoint(35, 120), new XuniPoint(85, 120), new XuniPoint(100, 80) }.ToList()
			});

			chart.Annotations.Add(new XuniChartEllipseAnnotation(chart)
			{
				IsVisible = true,
				Position = XuniChartAnnotationPosition.Center,
				Attachment = XuniChartAnnotationAttachment.Relative,
				Width = 60,
				Height = 40,
				Point = new XuniPoint(0.8, 0.3),
				Color = new UIColor(241.0f / 255.0f, 175.0f / 255.0f, 102.0f / 255.0f, 1.0f),
				BorderColor = new UIColor(188.0f / 255.0f, 136.0f / 255.0f, 80.0f / 255.0f, 1.0f),
				BorderWidth = 2,
				Text = "Relative",
				TooltipText = "Ellipse Annotation\\nPoint:{0.8,0.3}\\nAttachment:Relative"
			});

			double middleY = (chart.AxisY.ActualDataMax - chart.AxisY.ActualDataMin) / 2 + chart.AxisY.ActualDataMin;

			chart.Annotations.Add(new XuniChartLineAnnotation(chart)
			{
				IsVisible = true,
				Attachment = XuniChartAnnotationAttachment.DataCoordinate,
				Start = new XuniPoint(0, middleY),
				End = new XuniPoint(chart.AxisX.ActualDataMax, middleY),
				Color = UIColor.Blue,
				LineWidth = 3
			});

			chart.Annotations.Add(new XuniChartTextAnnotation(chart)
			{
				IsVisible = true,
				Position = XuniChartAnnotationPosition.Right,
				Attachment = XuniChartAnnotationAttachment.DataCoordinate,
				Width = 80,
				Height = 20,
				Point = new XuniPoint(0.3, middleY+200),
				Font = UIFont.BoldSystemFontOfSize(12),
				Text = "Data Coordinate"
			});

			chart.Annotations.Add(new XuniChartImageAnnotation(chart)
			{
				IsVisible = true,
				Position = XuniChartAnnotationPosition.Center,
				Attachment = XuniChartAnnotationAttachment.DataIndex,
				SeriesIndex = 0,
				PointIndex = 2,
				Width = 50,
				Height = 50,
				Offset = new XuniPoint(0,10),
				Source = new UIImage("Images/xuni_butterfly"),
				TooltipText = "Image Annotation\nPointIndex:{2}\nAttachment:DataIndex"
			});

			chart.Annotations.Add(new XuniChartRectangleAnnotation(chart)
			{
				IsVisible = true,
				Position = XuniChartAnnotationPosition.Center,
				Attachment = XuniChartAnnotationAttachment.DataIndex,
				SeriesIndex = 0,
				PointIndex = 3,
				Width = 100,
				Height = 50,
				BorderWidth = 2,
				Text = "DataIndex",
				TooltipText = "Rectangle Annotation\\nPointIndex:{6}\\nAttachment:DataIndex",
				Color = new UIColor(169.0f / 255.0f, 230.0f / 255.0f, 25.0f / 255.0f, 1.0f),
				BorderColor = new UIColor(34.0f / 255.0f, 166.0f / 255.0f, 60.0f / 255.0f, 1.0f)
			});
		}
	}
}
