// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using Xuni.iOS.Core;
using Xuni.iOS.ChartCore;
using Xuni.iOS.FlexChart;
using System.Linq;
using System.Collections.Generic;

namespace FlexChartSample
{
	public partial class CustomPlotElementsController : UIViewController
	{
		public CustomPlotElementsController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();


			var cList = new List<Company>
			{
				new Company { Name = "Apple", DevicesSold = 15.58} ,
				new Company { Name = "Google", DevicesSold = 20.23 },
				new Company { Name = "Microsoft", DevicesSold = 10.46 },
			};

			chart.ItemsSource = cList;

			chart.BindingX = "Name";
			chart.Series.Add(new Series(chart, "DevicesSold", "Devices Sold"));

			chart.IsAnimated = false;
			chart.Legend.Position = Position.None;
			chart.AxisY.AxisLineVisible = false;
			chart.AxisY.MajorTickWidth = 0;
			chart.AxisY.Title = "Devices Sold (billions)";
			chart.AxisY.TitleFont = UIFont.ItalicSystemFontOfSize(16);
			chart.AxisX.MajorTickWidth = 0;
			chart.AxisX.MinorTickWidth = 1;

			chart.IsHandleXFPlotElementLoading = true;

			chart.HandlePlotElementLoading += delegate (FlexChart sender, XuniRenderEngine renderEngine, XuniRect rect, int pointIndex, XuniPoint point, int seriesIndex, BasePlotElementRender defaultRender)
			{
				renderEngine.SetFillColor(UIColor.Gray);
				defaultRender.Execute();

				var img = cList[pointIndex].Name.ToLower();

				UIImage logo = new UIImage("Images/" + img);

				rect.Top += (rect.Height - rect.Width) / 2;
				rect.Height = rect.Width;

				logo.Draw(new CoreGraphics.CGRect(rect.Left, rect.Top, rect.Width, rect.Height));

				return true;
			};
		}

		public class Company
		{
			string name;
			public string Name
			{
				get
				{
					return name;
				}
				set
				{
					name = value;
				}
			}
			public double DevicesSold { get; set; }
		} 
	}
}
