// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using Xuni.iOS.Core;
using Xuni.iOS.ChartCore;
using Xuni.iOS.FlexChart;

namespace FlexChartSample
{
	public partial class CustomizingAxesController : UIViewController
	{
		public CustomizingAxesController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			chart.BindingX = "Name";
			chart.Series.Add(new Series(chart, "Sales, Sales", "Sales"));
			chart.Series.Add(new Series(chart, "Expenses, Expenses", "Expenses"));
			chart.ItemsSource = SalesData.GetSalesDataList();

			chart.AxisX.Title = "Country";
			chart.AxisX.LineWidth = 2;
			chart.AxisX.MinorTickWidth = 1;
			chart.AxisX.MajorTickWidth = 0;
			chart.AxisX.IsHandleXFAxisLabelLoading = true;

			chart.AxisY.LineWidth = 2;
			chart.AxisY.MinorGridVisible = true;
			chart.AxisY.MinorGridWidth = 0.5;
			chart.AxisY.MinorGridDashes = new double[]{ 4, 4};
			chart.AxisY.MinorTickWidth = 1;
			chart.AxisY.MajorTickWidth = 2;
			chart.AxisY.MajorGridWidth = 1;
			chart.AxisY.MajorGridColor = UIColor.FromWhiteAlpha(0.8f, 1.0f);
			chart.AxisY.MajorGridFill = UIColor.FromWhiteAlpha(0.6f, 0.2f); 
			chart.AxisY.MajorUnit = 1000;
			chart.AxisY.Max = 10000;
			chart.AxisY.IsHandleXFAxisLabelLoading = true;

			chart.HandleLabelLoading += delegate (FlexChart sender, XuniRenderEngine renderEngine, int axisIndex, XuniLabelLoadingEventArgs eventArgs) 
			{
				if (axisIndex == (int)AxisType.Y)
				{
					if (eventArgs.Value <= 3000)
					{
						renderEngine.SetTextFill(UIColor.Red);
					}
					else if (eventArgs.Value <= 10000 && eventArgs.Value > 6000)
					{
						renderEngine.SetTextFill(UIColor.Green);
					}
					else 
					{
						renderEngine.SetTextFill(UIColor.Black);
					}
					eventArgs.Label = "$" + (eventArgs.Value / 1000).ToString() + "K";

					return false;
				}
				else if (axisIndex == (int)AxisType.X)
				{
					UIImage img = new UIImage("Images/" + eventArgs.Label);
					img.Draw(new CoreGraphics.CGRect(eventArgs.Region.Left, eventArgs.Region.Top, eventArgs.Region.Width, eventArgs.Region.Height));
					eventArgs.Label = "";

					return true;
				}

				return false;
			};
		}
	}
}