// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FlexChartSample
{
	public partial class FinancialChartController : UIViewController
	{
		public FinancialChartController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			chart.BindingX = "Date";
			chart.Series.Add(new Xuni.iOS.FlexChart.Series(this.chart, "High,Low,Open,Close", "AAPL"));
			chart.ChartType = Xuni.iOS.FlexChart.ChartType.Candlestick;
			chart.SelectionMode = Xuni.iOS.ChartCore.SelectionMode.Point;
			chart.Legend.Position = Xuni.iOS.ChartCore.Position.None;
			chart.AxisY.MajorGridFill = new UIColor(0.6f, 0.2f);


			chart.ItemsSource = FinancialData.GetFinancialDataList();
		}

		partial void modeSwitched(UISegmentedControl sender)
		{
			switch (sender.SelectedSegment)
			{
				case 0:
					chart.ChartType = Xuni.iOS.FlexChart.ChartType.Candlestick;
					break;
				case 1:
					chart.ChartType = Xuni.iOS.FlexChart.ChartType.HighLowOpenClose;
					break;
			}

		}
	}
}
