// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FlexChartSample
{
	public partial class GettingStartedController : UIViewController
	{
		public GettingStartedController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			this.chart.BindingX = "Name";
			this.chart.Series.Add (new Xuni.iOS.FlexChart.Series (this.chart, "Sales, Sales", "Sales"));
			this.chart.Series.Add (new Xuni.iOS.FlexChart.Series (this.chart, "Expenses, Expenses", "Expenses"));
			this.chart.Series.Add (new Xuni.iOS.FlexChart.Series (this.chart, "Downloads, Downloads", "Downloads"));
			this.chart.ItemsSource = SalesData.GetSalesDataList ();
		}
	}
}
