// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using Xuni.iOS.Core;
using Xuni.iOS.ChartCore;
using Xuni.iOS.FlexChart;

namespace FlexChartSample
{
	public partial class LegendAndTitlesController : UIViewController
	{
		public LegendAndTitlesController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			chart.BindingX = "Name";
			chart.Series.Add(new Series(chart, "Sales, Sales", "Sales"));
			chart.Series.Add(new Series(chart, "Expenses, Expenses", "Expenses"));
			chart.Series.Add(new Series(chart, "Downloads, Downloads", "Downloads"));
			chart.ItemsSource = SalesData.GetSalesDataList();

			chart.ChartType = ChartType.Scatter;


			chart.Header = "Sample Chart";
			chart.HeaderTextColor = new UIColor(0.502f, 0.016f, 0.302f, 1);   
			chart.HeaderFont = UIFont.BoldSystemFontOfSize(24);
			chart.HeaderTextAlignment = HorizontalAlignment.Center;
			chart.Footer = "2015 GrapeCity, Inc.";
			chart.FooterTextColor = new UIColor(0.502f, 0.016f, 0.302f, 1);
			chart.FooterFont = UIFont.SystemFontOfSize(16);
			chart.FooterTextAlignment = HorizontalAlignment.Center;

			chart.AxisX.Title = "Country";
			chart.AxisX.TitleFont = UIFont.BoldSystemFontOfSize(16);
			chart.AxisX.TitleFont = UIFont.ItalicSystemFontOfSize(16);
			chart.AxisX.MajorGridVisible = true;
			chart.AxisY.Title = "Amount";
			chart.AxisY.TitleFont = UIFont.BoldSystemFontOfSize(16);
			chart.AxisY.TitleFont = UIFont.ItalicSystemFontOfSize(16);
			chart.AxisY.Format = "C0";

		}
	}
}
