// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

using Xuni.iOS.Core;
using Xuni.iOS.ChartCore;
using Xuni.iOS.FlexChart;


namespace FlexChartSample
{
	public partial class MultipleAxesController : UIViewController
	{
		public MultipleAxesController(IntPtr handle) : base(handle)
		{
		}

		public static IEnumerable<WeatherData> GetWeatherData()
		{
			List<WeatherData> weatherData = new List<WeatherData>();
			string[] monthNames = new string[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
			double[] tempData = new double[] { 24, 30, 45, 58, 68, 75, 83, 80, 72, 62, 47, 32 };
			Random random = new Random();

			for (int i = 0; i < monthNames.Length; i++)
			{
				WeatherData wd = new WeatherData();
				wd.MonthName = monthNames[i];
				wd.Precipitation = random.Next(8, 18) + random.NextDouble();
				wd.Temp = Math.Tan(i * i) + 70;
				weatherData.Add(wd);
			}
			return weatherData;
		}

		public class WeatherData
		{
			public string MonthName { get; set; }
			public double Temp { get; set; }
			public double Precipitation { get; set; }
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			chart.ItemsSource = GetWeatherData();

			chart.BindingX = "MonthName";

			Axis axisT = new Axis(Position.Right, chart)
			{
				Min = 0,
				Max = 80,
				MajorUnit = 10,
				Title = "Avg.Temperature(F)",
				AxisLineVisible = false,
				MajorGridVisible = false,
				MajorGridWidth = 1,
				MajorTickWidth = 0,
				TitleTextColor = new UIColor(0.984f, 0.698f, 0.345f, 1.0f),
				LabelsVisible = true
			};

			chart.AxesArray.Add(axisT);

			chart.Series.Add(new Series(chart, "Precipitation, Precipitation", "Precip"));
			chart.Series.Add(new Series(chart, "Temp, Temp", "Avg. Temp") { ChartType = ChartType.SplineSymbols, AxisY = axisT });



			chart.AxisY.Min = 4;
			chart.AxisY.Max = 20;
			chart.AxisY.MajorUnit = 2;
			chart.AxisY.Title = "Precipitation (in)";
			chart.AxisY.AxisLineVisible = false;
			chart.AxisY.MajorTickWidth = 1;
			chart.AxisY.MinorTickWidth = 0;
			chart.AxisY.TitleTextColor = new UIColor(0.533f, 0.741f, 0.902f, 1.0f);
			chart.AxisX.LabelAngle = 90;
			chart.AxisX.MajorGridVisible = false;
			chart.Legend.Position = Position.None;
		}

	}
}
