// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using Xuni.iOS.Core;
using Xuni.iOS.ChartCore;
using Xuni.iOS.FlexChart;
using System.Linq;
using System.Collections.Generic;


namespace FlexChartSample
{
	public partial class ScrollingController : UIViewController
	{
		public ScrollingController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			chart.ItemsSource = FinancialData.GetFinancialDataList();

			chart.Palette = XuniPalettes.Superhero;

			chart.BindingX = "Date";

			Axis axisT = new Axis(Position.Right, chart)
			{
				Min = 0,
				Max = 150,
				MajorUnit = 10,
				Title = "Volume",
				AxisLineVisible = false,
				MajorGridVisible = false,
				MajorGridWidth = 1,
				MajorTickWidth = 0,
				TitleTextColor = new UIColor(0.984f, 0.698f, 0.345f, 1.0f),
				LabelsVisible = true
			};

			chart.AxesArray.Add(axisT);

			chart.Series.Add(new Series(chart, "Volume", "Volume") { AxisY = axisT });
			chart.Series.Add(new Series(chart, "High", "High") { ChartType = ChartType.Line });
			chart.Series.Add(new Series(chart, "Low", "Low") { ChartType = ChartType.Line });

			chart.Header = "Drag to scroll/Pinch to zoom";
			chart.ZoomMode = ZoomMode.X;
			chart.AxisX.DisplayedRange = 10;
		}

 
	}
}
