// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using Xuni.iOS.Core;
using Xuni.iOS.ChartCore;
using Xuni.iOS.FlexChart;
using System.Linq;
using System.Collections.Generic;

namespace FlexChartSample
{
	public partial class SelectionModesController : UIViewController
	{
		public SelectionModesController (IntPtr handle) : base (handle)
		{
		}

		string[] chartTypes = { "Column", "Bar", "Scatter", "Line", "LineSymbol", "Area" };
		string[] chartSelection = { "None", "Series", "Point" };

		public class ChartTypesModel : UIPickerViewModel
		{
			SelectionModesController tk;

			public ChartTypesModel(SelectionModesController tk)
			{
				this.tk = tk;
			}

			public override nint GetComponentCount(UIPickerView v)
			{
				return 2;
			}

			public override nint GetRowsInComponent(UIPickerView pickerView, nint component)
			{
				if (component == 0)
					return tk.chartTypes.Length;
				else
					return tk.chartSelection.Length;
			}

			public override string GetTitle(UIPickerView picker, nint row, nint component)
			{
				if (component == 0)
					return tk.chartTypes[row];
				else
					return tk.chartSelection[row];
			}

			public override void Selected(UIPickerView picker, nint row, nint component)
			{
				if (component == 0)
				{
					if (row == 0)
					{
						tk.chart.ChartType = ChartType.Column;
					}
					else if (row == 1)
					{
						tk.chart.ChartType = ChartType.Bar;
					}
					else if (row == 2)
					{
						tk.chart.ChartType = ChartType.Scatter;
					}
					else if (row == 3)
					{
						tk.chart.ChartType = ChartType.Line;
					}
					else if (row == 4)
					{
						tk.chart.ChartType = ChartType.LineSymbols;
					}
					else if (row == 5)
					{
						tk.chart.ChartType = ChartType.Area;
					}
				}
				else if (component == 1)
				{
					if (row == 0)
					{
						tk.chart.SelectionMode = SelectionMode.None;

					}
					else if (row == 1)
					{
						tk.chart.SelectionMode = SelectionMode.Series;
					}
					else if (row == 2)
					{
						tk.chart.SelectionMode = SelectionMode.Point;
					}
				}

			}

		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			picker.Model = new ChartTypesModel(this);

			chart.BindingX = "Name";
			chart.Series.Add(new Series(chart, "Sales, Sales", "Sales"));
			chart.Series.Add(new Series(chart, "Expenses, Expenses", "Expenses"));
			chart.Series.Add(new Series(chart, "Downloads, Downloads", "Downloads"));
			chart.ItemsSource = SalesData.GetSalesDataList();

			chart.SelectionMode = SelectionMode.Series;
			chart.SelectedBorderColor = UIColor.Red;
			chart.SelectedBorderWidth = 3;
			chart.SelectedDashes = new double[] { 7.5, 2.5 };
		}

		public override void ViewWillAppear(bool animated)
		{
			base.ViewWillAppear(animated);

			picker.Select(0, 0, false);
			picker.Select(1, 1, false);
		}
	}
}
