// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FlexChartSample
{
	public partial class SnapshotController : UIViewController
	{
		public SnapshotController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			this.chart.BindingX = "Name";
			this.chart.Series.Add(new Xuni.iOS.FlexChart.Series(this.chart, "Sales, Sales", "Sales"));
			this.chart.Series.Add(new Xuni.iOS.FlexChart.Series(this.chart, "Expenses, Expenses", "Expenses"));
			this.chart.Series.Add(new Xuni.iOS.FlexChart.Series(this.chart, "Downloads, Downloads", "Downloads"));
			this.chart.ItemsSource = SalesData.GetSalesDataList();
		}

		partial void doSnapshot(UIBarButtonItem sender)
		{
			UIImage img = new UIImage(chart.GetImage());
			img.SaveToPhotosAlbum((image, error) =>
			{
				if (error == null)
					new UIAlertView("Success", "Image was saved to Camera Roll succesfully", null, "OK", null).Show();
				else
					new UIAlertView("Failure", error.Description, null, "OK", null).Show();
			});
		}
	}
}
