// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace FlexChartSample
{
	public partial class StylingSeriesController : UIViewController
	{
		public StylingSeriesController(IntPtr handle) : base(handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			this.chart.BindingX = "Name";
			this.chart.Series.Add(new Xuni.iOS.FlexChart.Series(this.chart, "Sales, Sales", "Sales")
			{
				Color = UIColor.Purple,
				BorderColor = UIColor.Green,
				BorderWidth = 2
			});
			this.chart.Series.Add(new Xuni.iOS.FlexChart.Series(this.chart, "Expenses, Expenses", "Expenses")
			{
				Color = UIColor.Red,
				BorderColor = new UIColor(0.502f, 0, 0, 1),
				BorderWidth = 2
			});
			this.chart.Series.Add(new Xuni.iOS.FlexChart.Series(this.chart, "Downloads, Downloads", "Downloads")
			{
				ChartType = Xuni.iOS.FlexChart.ChartType.LineSymbols,
				Color = new UIColor(1, 0.416f, 1, 1),
				BorderWidth = 10,
				SymbolColor = UIColor.Yellow,
				SymbolBorderColor = UIColor.Yellow,
				SymbolBorderWidth = 5
			});
			this.chart.ItemsSource = SalesData.GetSalesDataList();


		}
	}
}
