// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using Xuni.iOS.Core;
using Xuni.iOS.ChartCore;
using Xuni.iOS.FlexChart;
using System.Linq;
using System.Collections.Generic;

namespace FlexChartSample
{
	public partial class ToggleSeriesController : UIViewController
	{
		public ToggleSeriesController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			chart.BindingX = "Name";
			chart.Series.Add(new Series(chart, "Sales, Sales", "Sales"));
			chart.Series.Add(new Series(chart, "Expenses, Expenses", "Expenses"));
			chart.Series.Add(new Series(chart, "Downloads, Downloads", "Downloads"));
			chart.ItemsSource = SalesData.GetSalesDataList();

			chart.SelectionMode = SelectionMode.Series;
			chart.ChartType = ChartType.LineSymbols;


		}

		partial void switchChanged(UISwitch sender)
		{
			int index = (int)sender.Tag;
			if (sender.On)
			{
				chart.Series[index].Visibility = SeriesVisibility.Visible;
			}
			else
			{
				chart.Series[index].Visibility = SeriesVisibility.Hidden;
			}

		}
	}
}
